# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registered_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
    ]
